#!/bin/bash 

# Configuration first : set the local repository
# where the code can be found
# Test number of arguments 
if (( ! $# == 3 ))
then
    echo " Usage : bash_nukem repository_directory vm (should be senslab or senslab2) and \
    federation option (0 (not federated),1(other senslab) , 2(ple) 3 (senslab and ple))"
    echo  $#
    exit
fi

# Check if  directory exists
if [ -d $1 ]
then
    git_local_repo=$1
    echo "RESPOSITORY: "  $git_local_repo
   
fi

# Set which vm we are working on (sfa-vm or sfa-vm2)
if [[ $2 = "senslab" || $2 = "senslab2" ]]
then
    vm=$2
    echo $vm
else
    echo "Vm options should be senslab or senslab2, not " $2
    exit 
fi

if [ $vm = "senslab" ]
then
    federation_commented_line_nb=2
else
    federation_commented_line_nb=3
fi

# First restart sfa (prevents stalling when connecting
# to the DB and dropping tables)
sudo service sfa restart

# Nuke the database 
sudo sfaadmin.py registry nuke

# Drop table in slab_sfa
# to avoid duplicates.
psql -d slab_sfa -U sfa -W -q -c "drop table slice_senslab;"
psql -d slab_sfa -U sfa -W -q -c "drop table slab_xp;"

# ATTENTION :Save the config file /etc/sfa/sfa_config
# before continuing

# Remove all the remaining gid, creds files
# of the server
sudo rm -rf /var/lib/sfa
cd /etc/sfa
sudo rm -rf *
sudo service sfa restart

# Put back the config file that you saved before
cd $git_local_repo
sudo make clean
make
sudo python setup.py install
# sudo service sfa restart

# Wrote /etc/sfa/configs/site.xml
# Merged
#         /etc/sfa/default_config.xml
# and     /etc/sfa/configs/site.xml
# into    /etc/sfa/sfa_config.xml
# sudo sfa-config-tty
# 
#sudo cp $git_local_repo/sfa/senslab/config/$vm/sfa_config /etc/sfa/sfa_config
sudo cp $git_local_repo/sfa/senslab/config/$vm/sfa_config.xml /etc/sfa/sfa_config.xml
sudo cp $git_local_repo/sfa/senslab/config/$vm/default_config.xml /etc/sfa/default_config.xml
# sudo cp $git_local_repo/sfa/senslab/config/$vm/site.xml  /etc/sfa/site.xml
# sudo cp $git_local_repo/sfa/senslab/config/$vm/site_config  /etc/sfa/configs/site_config
# sudo ln -s ldap_config.py  /etc/sfa/ldap_config.py


#Senslab LDAP and OAR access config files
if [ ! -f /etc/sfa/ldap_config.py ] 
then
    sudo cp $git_local_repo/sfa/senslab/config/ldap_config.py  /etc/sfa/ldap_config.py 
fi

if [ ! -f /etc/sfa/oar_config.py ] 
then
    sudo cp $git_local_repo/sfa/senslab/config/oar_config.py  /etc/sfa/oar_config.py 
fi

sudo service sfa restart

# User stuff : clean your folder
cd  ~/.sfi
rm *.sscert *.cred *.gid sfi_cache.dat
cd ~

# Import the datbase form ldap
sudo sfaadmin.py registry import_registry
sudo service sfa restart

sudo cp $git_local_repo/sfa/senslab/config/registries.xml /etc/sfa/registries.xml
sudo cp $git_local_repo/sfa/senslab/config/aggregates.xml /etc/sfa/aggregates.xml


case "$3" in
    0) echo "No federation at all"
        #Insert a # on every beginning of line except if there is 'aggregates'
        sed -i '/aggregates/!s/^/#/g' /etc/sfa/aggregates.xml 
        sed -i '/registries/!s/^/#/g' /etc/sfa/registries.xml   
        ;;
    1) echo "Setting up federation with other senslab "
        #  Commenting out senslab and ple, lines 2 and 4 OR
        #  Commenting out senslab2 and ple, lines 3 and 4
        sed -i "${federation_commented_line_nb} s/^/#/" /etc/sfa/aggregates.xml 
        sed -i "${federation_commented_line_nb} s/^/#/" /etc/sfa/registries.xml 
        sed -i '4 s/^/#/' /etc/sfa/aggregates.xml 
        sed -i '4 s/^/#/' /etc/sfa/registries.xml 
        ;;

    2) echo "Setting up federation with  ple " 
        sed -i '2 s/^/#/' /etc/sfa/aggregates.xml 
        sed -i '2 s/^/#/' /etc/sfa/registries.xml 
        sed -i '3 s/^/#/' /etc/sfa/aggregates.xml 
        sed -i '3 s/^/#/' /etc/sfa/registries.xml 
        ;;  

    3) echo "setting federation with other senslab and ple"
        # Commenting out senslab or senslab2
        sed -i "${federation_commented_line_nb} s/^/#/" /etc/sfa/aggregates.xml 
        sed -i "${federation_commented_line_nb} s/^/#/" /etc/sfa/registries.xml 
        ;;
esac

sudo service sfa restart

sudo rm -rf /var/lib/sfa/authorities/plc
