usr/bin/sfa-start.py*
usr/bin/sfaadmin.py*
#usr/bin/sfaadmin
usr/bin/keyconvert.py*
usr/bin/sfa-config-tty
usr/bin/sfa-config
etc/sfa/default_config.xml
etc/sfa/aggregates.xml
etc/sfa/registries.xml
etc/init.d/sfa
etc/init.d/functions.sfa
usr/share/sfa/migrations
usr/share/sfa/examples
#var/www/html/wsdl/*.wsdl
wsdl/sfa.wsdl var/www/html/wsdl/
wsdl/registry.wsdl var/www/html/wsdl/
wsdl/aggregate.wsdl var/www/html/wsdl/
wsdl/slice-manager.wsdl var/www/html/wsdl/
