#!/bin/bash
if (( ! $# == 2 ))
then
    echo " Usage : bash_test takes 2 arguments : one jobid and one of the following:"
    echo " LDAP/ OAR / driver "
    echo  $#
    exit
fi

sfi.py list iotlab
echo " =================    SFI.PY RESOURCES            ============="
sfi.py resources

echo " ================= SFI.PY RESOURCES -R SLAB        ============="
sfi.py resources -r iotlab

echo " =================    SFI.PY RESOURCES -L ALL      ============="
sfi.py resources -l all

echo " ================= SFI.PY RESOURCES -R SLAB -L ALL ============="
sfi.py resources -r iotlab -l all

echo " ================= SFI.PY RESOURCES -L ALL > avakian_adv.rspec ============="
sfi.py resources -l all > /root/tests_rspecs/iotlab_devlille_OUTPUT.rspec

echo " ================= SFI.PY RESOURCES avakian_adv.rspec ============="
sfi.py resources iotlab.avakian_slice


echo " =================    SFI.PY SHOW SLICE   ============="
sfi.py show iotlab.avakian_slice

echo " =================    SFI.PY SHOW USER   ============="
sfi.py show iotlab.avakian

echo " =================    SFI.PY SHOW NODE   ============="
sfi.py show iotlab.node6.devlille.senslab.info

echo " =================    SFI.PY SLICES       ============="
sfi.py slices

echo " =================    SFI.PY STATUS SLICE   ============="
sfi.py status iotlab.avakian_slice

echo " =================    SFI.PY CREATE SLICE   ============="
sfi.py create iotlab.avakian_slice /root/tests_rspecs/iotlab_devlille.rspec

# echo " =================    SFI.PY DELETE SLICE   ============="
# sfi.py delete iotlab.avakian_slice

echo "\r\n"
echo " PYTHON TEST ", $1, $2
