#!/usr/bin/env python

import os


print " =================    SFI.PY LIST IOTLAB        ============="
os.system('sfi.py list iotlab')


print " =================    SFI.PY RESOURCES          ============="
input("Press Enter to continue...")
os.system('sfi.py resources')

print " ================= SFI.PY RESOURCES -R IOTLAB        ============="
input("Press Enter to continue...")
os.system('sfi.py resources -r iotlab')

print " =================    SFI.PY RESOURCES -L ALL      ============="
input("Press Enter to continue...")
os.system('sfi.py resources -l all')

print " ================= SFI.PY RESOURCES -R IOTLAB -L ALL ============="
input("Press Enter to continue...")
os.system('sfi.py resources -r iotlab -l all')

print " ================= SFI.PY RESOURCES -L ALL > avakian_adv.rspec ==========="
os.system('sfi.py resources -l all > /root/tests_rspecs/iotlab_devlille_OUTPUT.rspec')

print " ================= SFI.PY RESOURCES -L LEASES  ============="
input("Press Enter to continue...")
os.system('sfi.py resources -l leases')

print " =================SFI.PY RESOURCES -L LEASES -R IOTLAB ============== "
os.system('sfi.py resources -r iotlab -l leases')

print " ================= SFI.PY RESOURCES avakian_adv.rspec ============="
input("Press Enter to continue...")
os.system('sfi.py resources iotlab.avakian_slice')


print " =================    SFI.PY SHOW SLICE   ============="
os.system('sfi.py show iotlab.avakian_slice')

print " =================    SFI.PY SHOW USER   ============="
input("Press Enter to continue...")
os.system('sfi.py show iotlab.avakian')

print " =================    SFI.PY SHOW NODE   ============="
os.system('sfi.py show iotlab.node6.devlille.senslab.info')

print " =================    SFI.PY SLICES       ============="
input("Press Enter to continue...")
os.system('sfi.py slices')

print " =================    SFI.PY STATUS SLICE   ============="
os.system('sfi.py status iotlab.avakian_slice')

print " =================    SFI.PY CREATE SLICE   ============="
input("Press Enter to continue...")
os.system('sfi.py create iotlab.avakian_slice /root/tests_rspecs/iotlab_devlille.rspec')


print " =================    SFI.PY DELETE SLICE   ============="
input("Press Enter to continue...")
os.system('sfi.py delete iotlab.avakian_slice')
print "\r\n"

